version: "3"
services:
    php:
        image: vasiliishvakin/php:7.4-fpm-development
        container_name: php
        ports:
            - "0.0.0.0:9000:9000"
        volumes:
            - "../:/workspace"
            - "../cache/composer:/root/.cache/composer"
            - "../cache/vscode-extensions-cache:/vscode/vscode-server/extensionsCache"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /app

    caddy:
        image: caddy:2-alpine
        container_name: caddy
        ports:
            - "0.0.0.0:80:80"
        volumes:
            - "../:/workspace"
            - "../data/caddy:/data"
            - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /app

    mysql:
        image: mariadb:latest
        container_name: mysql
        ports:
            - "0.0.0.0:3306:3306"
        volumes:
            - "../data/mysql:/var/lib/mysql"
            - "./mysql/conf.d:/etc/mysql/conf.d"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
        extra_hosts:
            - "host.docker.internal:host-gateway"
